[project]
name = "enveda-casmi-26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mardhav-2008", email = "mardhavrayapati81@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
enveda-casmi-26 = "enveda_casmi_26:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
